startServices: "s3,sqs"
service:
  type: ClusterIP
enableStartupScripts: true
startupScriptContent: |
  #!/bin/bash
  awslocal sqs create-queue --queue-name tacoshop
  awslocal s3api create-bucket --bucket tacoshop